spring:
  application:
    name: big-event
  servlet:
    multipart:
      max-file-size: 5MB
  devtools:
    restart:
      enabled: true
      quiet-period: 1500ms
      poll-interval: 3000ms
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/big_event?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: redis
      port: 6379
      password: redis@123
      database: 2
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true